In [1]:
import pandas as pd
import numpy as np

# Geting the data

In [2]:
cat=pd.read_csv('categorical.csv')
num=pd.read_csv('numerical.csv')
tar=pd.read_csv('target.csv')

In [3]:
data=pd.concat([num,cat,tar],axis=1)

In [4]:
data

,TCODE,AGE,INCOME,WEALTH1,HIT,MALEMILI,MALEVET,VIETVETS,WWIIVETS,LOCALGOV,...,MINRDATE_YR,MINRDATE_MM,MAXRDATE_YR,MAXRDATE_MM,LASTDATE_YR,LASTDATE_MM,FIRSTDATE_YR,FIRSTDATE_MM,TARGET_B,TARGET_D
0,0,60.000000,5,9,0,0,39,34,18,10,...,92,8,94,2,95,12,89,11,0,0.0
1,1,46.000000,6,9,16,0,15,55,11,6,...,93,10,95,12,95,12,93,10,0,0.0
2,1,61.611649,3,1,2,0,20,29,33,6,...,91,11,92,7,95,12,90,1,0,0.0
3,0,70.000000,1,4,2,0,23,14,31,3,...,87,11,94,11,95,12,87,2,0,0.0
4,0,78.000000,3,2,60,1,28,9,53,26,...,93,10,96,1,96,1,79,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95407,1,61.611649,5,9,0,14,36,47,11,7,...,96,2,96,2,96,2,96,2,0,0.0
95408,1,48.000000,7,9,1,0,31,43,19,4,...,96,3,96,3,96,3,96,3,0,0.0
95409,1,60.000000,5,9,0,0,18,46,20,7,...,96,3,95,1,96,10,94,10,0,0.0
95410,0,58.000000,7,9,0,0,28,35,20,9,...,90,11,96,8,97,1,86,12,1,18.0
95411,2,80.000000,5,8,3,1,33,22,27,8,...,88,12,93,12,96,12,88,3,0,0.0

In [5]:
data.columns.to_list()

['TCODE',
 'AGE',
 'INCOME',
 'WEALTH1',
 'HIT',
 'MALEMILI',
 'MALEVET',
 'VIETVETS',
 'WWIIVETS',
 'LOCALGOV',
 'STATEGOV',
 'FEDGOV',
 'WEALTH2',
 'POP901',
 'POP902',
 'POP903',
 'POP90C1',
 'POP90C2',
 'POP90C3',
 'POP90C4',
 'POP90C5',
 'ETH1',
 'ETH2',
 'ETH3',
 'ETH4',
 'ETH5',
 'ETH6',
 'ETH7',
 'ETH8',
 'ETH9',
 'ETH10',
 'ETH11',
 'ETH12',
 'ETH13',
 'ETH14',
 'ETH15',
 'ETH16',
 'AGE901',
 'AGE902',
 'AGE903',
 'AGE904',
 'AGE905',
 'AGE906',
 'AGE907',
 'CHIL1',
 'CHIL2',
 'CHIL3',
 'AGEC1',
 'AGEC2',
 'AGEC3',
 'AGEC4',
 'AGEC5',
 'AGEC6',
 'AGEC7',
 'CHILC1',
 'CHILC2',
 'CHILC3',
 'CHILC4',
 'CHILC5',
 'HHAGE1',
 'HHAGE2',
 'HHAGE3',
 'HHN1',
 'HHN2',
 'HHN3',
 'HHN4',
 'HHN5',
 'HHN6',
 'MARR1',
 'MARR2',
 'MARR3',
 'MARR4',
 'HHP1',
 'HHP2',
 'DW1',
 'DW2',
 'DW3',
 'DW4',
 'DW5',
 'DW6',
 'DW7',
 'DW8',
 'DW9',
 'HV1',
 'HV2',
 'HV3',
 'HV4',
 'HU1',
 'HU2',
 'HU3',
 'HU4',
 'HU5',
 'HHD1',
 'HHD2',
 'HHD3',
 'HHD4',
 'HHD5',
 'HHD6',
 'HHD7',
 'HHD8',
 'HHD9',
 'HHD10',
 'HHD11',
 'HHD12',
 'ETHC1',
 'ETHC2',
 'ETHC3',
 'ETHC4',
 'ETHC5',
 'ETHC6',
 'HVP1',
 'HVP2',
 'HVP3',
 'HVP4',
 'HVP5',
 'HVP6',
 'HUR1',
 'HUR2',
 'RHP1',
 'RHP2',
 'RHP3',
 'RHP4',
 'HUPA1',
 'HUPA2',
 'HUPA3',
 'HUPA4',
 'HUPA5',
 'HUPA6',
 'HUPA7',
 'RP1',
 'RP2',
 'RP3',
 'RP4',
 'MSA',
 'ADI',
 'DMA',
 'IC1',
 'IC2',
 'IC3',
 'IC4',
 'IC5',
 'IC6',
 'IC7',
 'IC8',
 'IC9',
 'IC10',
 'IC11',
 'IC12',
 'IC13',
 'IC14',
 'IC15',
 'IC16',
 'IC17',
 'IC18',
 'IC19',
 'IC20',
 'IC21',
 'IC22',
 'IC23',
 'HHAS1',
 'HHAS2',
 'HHAS3',
 'HHAS4',
 'MC1',
 'MC2',
 'MC3',
 'TPE1',
 'TPE2',
 'TPE3',
 'TPE4',
 'TPE5',
 'TPE6',
 'TPE7',
 'TPE8',
 'TPE9',
 'PEC1',
 'PEC2',
 'TPE10',
 'TPE11',
 'TPE12',
 'TPE13',
 'LFC1',
 'LFC2',
 'LFC3',
 'LFC4',
 'LFC5',
 'LFC6',
 'LFC7',
 'LFC8',
 'LFC9',
 'LFC10',
 'OCC1',
 'OCC2',
 'OCC3',
 'OCC4',
 'OCC5',
 'OCC6',
 'OCC7',
 'OCC8',
 'OCC9',
 'OCC10',
 'OCC11',
 'OCC12',
 'OCC13',
 'EIC1',
 'EIC2',
 'EIC3',
 'EIC4',
 'EIC5',
 'EIC6',
 'EIC7',
 'EIC8',
 'EIC9',
 'EIC10',
 'EIC11',
 'EIC12',
 'EIC13',
 'EIC14',
 'EIC15',
 'EIC16',
 'OEDC1',
 'OEDC2',
 'OEDC3',
 'OEDC4',
 'OEDC5',
 'OEDC6',
 'OEDC7',
 'EC1',
 'EC2',
 'EC3',
 'EC4',
 'EC5',
 'EC6',
 'EC7',
 'EC8',
 'SEC1',
 'SEC2',
 'SEC3',
 'SEC4',
 'SEC5',
 'AFC1',
 'AFC2',
 'AFC3',
 'AFC4',
 'AFC5',
 'AFC6',
 'VC1',
 'VC2',
 'VC3',
 'VC4',
 'ANC1',
 'ANC2',
 'ANC3',
 'ANC4',
 'ANC5',
 'ANC6',
 'ANC7',
 'ANC8',
 'ANC9',
 'ANC10',
 'ANC11',
 'ANC12',
 'ANC13',
 'ANC14',
 'ANC15',
 'POBC1',
 'POBC2',
 'LSC1',
 'LSC2',
 'LSC3',
 'LSC4',
 'VOC1',
 'VOC2',
 'VOC3',
 'HC1',
 'HC2',
 'HC3',
 'HC4',
 'HC5',
 'HC6',
 'HC7',
 'HC8',
 'HC9',
 'HC10',
 'HC11',
 'HC12',
 'HC13',
 'HC14',
 'HC15',
 'HC16',
 'HC17',
 'HC18',
 'HC19',
 'HC20',
 'HC21',
 'MHUC1',
 'MHUC2',
 'AC1',
 'AC2',
 'CARDPROM',
 'NUMPROM',
 'CARDPM12',
 'NUMPRM12',
 'RAMNTALL',
 'NGIFTALL',
 'CARDGIFT',
 'MINRAMNT',
 'MAXRAMNT',
 'LASTGIFT',
 'TIMELAG',
 'AVGGIFT',
 'CONTROLN',
 'HPHONE_D',
 'RFA_2F',
 'CLUSTER2',
 'STATE',
 'CLUSTER',
 'HOMEOWNR',
 'GENDER',
 'DATASRCE',
 'RFA_2R',
 'RFA_2A',
 'GEOCODE2',
 'DOMAIN_A',
 'DOMAIN_B',
 'ODATEW_YR',
 'ODATEW_MM',
 'DOB_YR',
 'DOB_MM',
 'MINRDATE_YR',
 'MINRDATE_MM',
 'MAXRDATE_YR',
 'MAXRDATE_MM',
 'LASTDATE_YR',
 'LASTDATE_MM',
 'FIRSTDATE_YR',
 'FIRSTDATE_MM',
 'TARGET_B',
 'TARGET_D']

In [6]:
data['TARGET_B'].value_counts()

0    90569
1     4843
Name: TARGET_B, dtype: int64

## correcting the imbalance

In [7]:
#downsample using logic -- hecho a lo bruto

category_0= data[data['TARGET_B']==0].sample(len(data[data['TARGET_B']==1]))

In [8]:
category_1=(data[data['TARGET_B']==1])

In [9]:
#now we gona recreate data?

data=pd.concat([category_0,category_1], axis=0)
data.reset_index(inplace=True,drop=True)
data.shape

(9686, 339)

In [10]:
data['TARGET_B'].value_counts()

0    4843
1    4843
Name: TARGET_B, dtype: int64

## pre processing

In [11]:
#split ya
X=data.drop(['TARGET_B'],axis=1)
Y=data['TARGET_B']

In [12]:
#hacer categorical y numerical

numericals = X.select_dtypes(np.number)
categoricals= X.select_dtypes(object)

In [13]:
### one hot encoder

from sklearn.preprocessing import OneHotEncoder as ohe

encoder = ohe(drop='first').fit(categoricals)   #hace el encoder pero quita una de las columnas que es complementaria al resto
cat_enc=encoder.transform(categoricals).toarray()
cat_enc_cols=encoder.get_feature_names_out(categoricals.columns)
cat_enc_df=pd.DataFrame(cat_enc, columns=cat_enc_cols)

In [14]:
#join back the numbers

X_full=pd.concat([cat_enc_df,numericals],axis=1)

In [15]:
X_full.shape

(9686, 355)

## train test split and model

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
#split train test
X_train,X_test,Y_train,Y_test=train_test_split(X_full,Y,test_size=0.3,random_state=42)

In [19]:
from sklearn.ensemble import RandomForestClassifier as rfc

In [21]:
# hagamos nuestro modelo de random forest con parametros y lo fiteamos
clf=rfc(n_estimators=50,max_depth=5,random_state=1)
clf.fit(X_train,Y_train)

RandomForestClassifier(max_depth=5, n_estimators=50, random_state=1)

In [22]:
#miremos que tal ha ido

print(clf.score(X_test,Y_test))

0.9965588437715073

## cross validation

- proxy test for overfit

In [23]:
from sklearn.model_selection import cross_val_score

In [24]:
cross_val_scores=cross_val_score(clf,X_train,Y_train,cv=10)
np.mean(cross_val_scores)

0.9905604719764012

## feature importance

In [25]:
#once we have the rforest we can get the features importance

feature_importance=clf.feature_importances_

In [27]:
feauter_names=X_full.columns